StudentHelp/urls.py
from django.contrib import admin
from django.urls import path ,include 
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('posts/', include('posts.urls')),
    path('profile/', include('profil.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='student/registration/login.html'), name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='student/registration/logout.html'), name ='logout'),
    

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts import views
from profil import views
from .views import ModifieStage ,ModifierLogement,ModifierRec,ModifierEvC,ModifierTransport,ModifierEvS
from posts.views import ListePost , SelectFormView, CreerPostView ,ListPostRecommandation,ListPostTra,ListPostEvenementClub,ListPostLogement,ListEvenementSocial,ListPostStage, supprimer_EvC, supprimer_EvS, supprimer_Logement, supprimer_Rec, supprimer_Stage, supprimer_Transport
urlpatterns = [
     path('', ListePost.as_view(), name='liste_posts'),
    path('creer_post/', SelectFormView.as_view(), name='select_form'),
    path('creer_post/<str:form_type>/', CreerPostView.as_view(), name='creer_post'),
    path('liste_stage/',ListPostStage.as_view(), name='liststage'),
    path('liste_recommandation/',ListPostRecommandation.as_view(), name='listRecommandation'),
    path('liste_evenementClub/',ListPostEvenementClub.as_view(), name='listEvenC'),
    path('liste_transport/',ListPostTra.as_view(), name='listTransport'),
    path('liste_logement/',ListPostLogement.as_view(), name='listLog'),
    path('liste_evenementSocial/',ListEvenementSocial.as_view(), name='listEvenS'),
    path('<int:pk>/modif_stage/',ModifieStage.as_view(),name='modif_stage'),
     path('<int:pk>/modif_Logement/', ModifierLogement.as_view(),name='modif_Logement'),
     path('<int:pk>/modif_Rec/', ModifierRec.as_view(),name='modif_Rec'),
     path('<int:pk>/modif_EvC/', ModifierEvC.as_view(),name='modif_EvC'),
     path('<int:pk>/modif_EvS/', ModifierEvS.as_view(),name='modif_EvS'),
     path('<int:pk>/modif_Transport/', ModifierTransport.as_view(),name='modif_Transport'),
    path('supprimer_Stage/<int:poste_id>/', supprimer_Stage, name='supprimer_Stage'),
    path('supprimer_Logement/<int:poste_id>/', supprimer_Logement, name='supprimer_Logement'),
    path('supprimer_Rec/<int:poste_id>/', supprimer_Rec, name='supprimer_Rec'),
     path('supprimer_Transport/<int:poste_id>/', supprimer_Transport, name='supprimer_Transport'),
     path('supprimer_EvS/<int:poste_id>/', supprimer_EvS, name='supprimer_EvS'),
     path('supprimer_EvC/<int:poste_id>/', supprimer_EvC, name='supprimer_EvC'),
    
]

profil/urls.py
from django.urls import path
from profil.views import modifier_poste,  user_profil
from profil import views

urlpatterns = [
    path('user/<int:user_id>/', user_profil, name='user_profil'),
    path('user/<int:user_id>/poste/<int:poste_id>/modifier/', modifier_poste, name='modifier_poste'),
    path('<int:pk>/supprimer/', views.SupprimerPost.as_view(), name='SupprimerPost'),

]

posts/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
# Create your models here.

class Poste(models.Model): 
    TYPE_CHOICES = [('0', 'offre'), ('1', 'demande')]
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    date = models.DateField(null=True, default=date.today)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.get_type_display() + ' - ' + str(self.date)



class Stage(Poste):
    TYPE_CHOICES = [('1', 'ouvrier'), ('2', 'technicien'), ('3', 'pfe')]
    typeStg = models.CharField(max_length=1, choices=TYPE_CHOICES)
    société = models.CharField(max_length=50) 
    durée = models.IntegerField()
    sujet = models.CharField(max_length=50)
    contactinfo = models.CharField(max_length=50)
    spécialite = models.CharField(max_length=255)

    def __str__(self): 
        return 'Stage - ' + self.société + ' - ' + self.sujet

profil/models.py
from django.db import models

# Create your models here.

profil/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy 
from posts.forms import PostForm
from posts.models import Poste 
from django.views.generic import DeleteView
from django.shortcuts import get_object_or_404, redirect, render





class SupprimerPost(DeleteView):
    model = Poste
    template_name = 'supprimer_Poste.html'
    success_url = reverse_lazy('user_profil')

    def get_success_url(self):
        user_id = self.object.user.id
        return reverse_lazy('user_profil', kwargs={'user_id': user_id})


def user_profil(request, user_id): 
    user = get_object_or_404(User, pk=user_id)
    user_posts = Poste.objects.filter(user=user)
    return render(request, 'user_profil.html', {'user': user, 'posts': user_posts})




def modifier_poste(request, user_id, poste_id):
    poste = get_object_or_404(Poste, pk=poste_id)
    user = get_object_or_404(User, pk=user_id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=poste)
        if form.is_valid():
            form.save()
            return redirect('user_profil', user_id=poste.user.id)
    else:
        form = PostForm(instance=poste)
    return render(request, 'modifier_poste.html', {'form': form})

profil/templates/modifier_poste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Créer le Post</title>
    {% extends "student/base.html" %} 
    {% block content %}
    <style>
        .formulaire {
          margin-top: 15px;
            max-width: 500px;
            margin: 0 auto;
            padding: 30px;
            border-radius: 10px;
            background-color: #2c2c2c; 
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2); 
        }
        form input[type="file"],
        select,
        form input[type="number"],
        form input[type="text"],
        form input[type="email"],
        form textarea {
            width: 100%;
            padding: 12px;
            margin-bottom: 20px;
            border: 1px solid #555; 
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
            background-color: #444; 
            color: #fff; /
        }

       
        form label {
            color: #fff; 
            margin-bottom: 5px;
            display: block;
        }

       
        .bouton {
            width: 100%;
            background-color: #3a3939; 
            color: #fff;
            padding: 15px 0;
            font-size: 18px;
            font-weight: 600;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .bouton:hover {
            background-color: #000000; /
        }
    </style>
</head>
<body>
  <br><br>
    <form class="formulaire" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="bouton" type="submit">Modifier</button>
    </form>
    {% endblock %}
</body>
</html>

profil/templates/supprimer_poste.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Supprimer le Post : {{ Post.nom }}</title>
    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <style>
      body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
        font-family: "Arial", sans-serif;
        background-color: #f0f0f0; /* Optionnel: couleur de fond douce */
      }
      .message-container {
        text-align: center;
        background: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
      h1 {
        color: #333;
        margin-bottom: 20px;
      }
      .btn-danger {
        color: white;
        background-color: red;
        padding: 10px 20px;
        text-decoration: none;
        border-radius: 5px;
        display: inline-block;
        transition: background-color 0.3s;
      }
      .btn-danger:hover {
        background-color: darkred;
      }
    </style>
  </head>
  <body>
    <div class="container message-container">
      <h1 class="display-4">
        Êtes-vous sûr de vouloir supprimer cet post 
      </h1>
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Oui, supprimer</button>
      </form>
    </div>
  </body>
</html>

profil/templates/user_profil.html
<!DOCTYPE html>
<html lang="en">
  
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" />
  {% extends "student/base.html" %}
  {% block content %}
    
</head>

<body>
  <div class="container">

    <div class="card overflow-hidden">
      <div class="card-body p-0">
       
        <img src="/media/palestine2.jpg" alt class="img-fluid" />
        <div class="mt-n3 order-lg-2 order-1">
          <div class="mt-n5">
            <div class="d-flex align-items-center justify-content-center">
              <div class="border border-4 border-white d-flex align-items-center justify-content-center rounded-circle overflow-hidden" style="width: 100px; height: 100px">
                <img src="https://img.freepik.com/vecteurs-premium/illustration-vectorielle-plate-echelle-gris-avatar-profil-utilisateur-icone-personne-image-profil-silhouette-neutre-genre-convient-pour-profils-medias-sociaux-icones-economiseurs-ecran-comme-modelex9xa_719432-879.jpg" alt class="w-100 h-100" />
              </div>
            </div>
          </div>
         
          <div class="text-center">
            <h5 class="fs-5 mb-0 fw-semibold">
              {% for poste in posts %}
              {% if forloop.first %}
              {{ poste.user }}
              {% endif %}
              {% endfor %}  
            </h5>
            
          </div>
         
          <div class="row align-items-center">
            <div class="">
              <div class="d-flex align-items-center justify-content-around m-4">
                <div class="text-center">
                  <i class="fa fa-file fs-6 d-block mb-2"></i>
                  <h4 class="mb-0 fw-semibold lh-1">15</h4>
                  <p class="mb-0 fs-4">Posts</p>
                </div>
                <div class="text-center">
                  <i class="fa fa-user fs-6 d-block mb-2"></i>
                  <h4 class="mb-0 fw-semibold lh-1">100k</h4>
                  <p class="mb-0 fs-4">Followers</p>
                </div>
                <div class="text-center">
                  <i class="fa fa-check fs-6 d-block mb-2"></i>
                  <h4 class="mb-0 fw-semibold lh-1">509</h4>
                  <p class="mb-0 fs-4">Following</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row mt-4">
        {% for poste in posts %}
        <div class="col-md-6 col-lg-4">
          <div class="card hover-img overflow-hidden rounded-2">
            <div class="card-body p-0">
              {% if poste.image %}
                <img src="{{ poste.image.url }}" alt="Post Image" class="img-fluid w-100" style="height: 350px" />
              {% endif %}
              <div class="p-4 d-flex align-items-center justify-content-between">
                <div>
                  <h6 class="fw-semibold mb-0 fs-4">{{ poste.title }}</h6>
                  <span class="text-dark fs-2">{{ poste.date }}</span>
                  <p>Type: {% if poste.type == '0' %}Offre{% else %}Demande{% endif %}</p>
                  {% if poste.evénement %}
                    {% if poste.evénement.evenclub %}
                      <h3>Événement de Club</h3>
                      <p>Club: {{ poste.evénement.evenclub.club }}</p>
                      <p>Intitulé: {{ poste.evénement.intitulé }}</p>
                      <p>Description: {{ poste.evénement.description }}</p>
                      <p>Lieu: {{ poste.evénement.lieu }}</p>
                      <p>Contact: {{ poste.evénement.contactInfo }}</p>
                    {% elif poste.evénement.evensocial %}
                      <h3>Événement Social</h3>
                      <p>Intitulé: {{ poste.evénement.intitulé }}</p>
                      <p>Description: {{ poste.evénement.description }}</p>
                      <p>Lieu: {{ poste.evénement.lieu }}</p>
                      <p>Contact: {{ poste.evénement.contactInfo }}</p>
                      <p>Prix: {{ poste.evénement.evensocial.prix }}</p>
                    {% endif %}
                  {% elif poste.logement %}
                    <h3>Logement</h3>
                    <p>Localisation: {{ poste.logement.localisation }}</p>
                    <p>Description: {{ poste.logement.description }}</p>
                    <p>Contact: {{ poste.logement.contactinfo }}</p>
                  {% elif poste.transport %}
                    <h3>Transport</h3>
                    <p>Départ: {{ poste.transport.depart }}</p>
                    <p>Destination: {{ poste.transport.destination }}</p>
                    <p>Heure de départ: {{ poste.transport.heure_dep }}</p>
                    <p>Nombre de sièges: {{ poste.transport.nbre_sièges }}</p>
                    <p>Contact: {{ poste.transport.contactinfo }}</p>
                  {% elif poste.stage %}
                    <h3>Stage</h3>
                    <p>Spécialité: {{ poste.stage.get_spécialite_display }}</p>
                    <p>Type: {{ poste.stage.get_typeStg_display }}</p>
                    <p>Société: {{ poste.stage.société }}</p>
                    <p>Durée: {{ poste.stage.durée }}</p>
                    <p>Sujet: {{ poste.stage.sujet }}</p>
                    <p>Contact: {{ poste.stage.contactinfo }}</p>
                  {% elif poste.recommandation %}
                    <h3>Recommandation</h3>
                    <p>Texte: {{ poste.recommandation.text }}</p>
                  {% endif %}
                  {% if user == request.user %}
                  <a href="{% url 'modifier_poste' user_id=poste.user.id poste_id=poste.id %}">Modifier</a>
                  <a href="{% url 'SupprimerPost' pk=poste.pk %}">Supprimer</a>   
                  {% endif %}
                  
                </div>
              </div>
            </div>
        </div>
      </div>
    </li>
    {% empty %}
        Aucun poste trouvé pour cet utilisateur.</li>
    {% endfor %}

      
    </div>
  
</div>
{% endblock %}
</body>
</html>